version: '2'
services:
  icinga2:
    image: jordan/icinga2
    restart: on-failure:5
    hostname: icinga2
    environment:
      - ICINGA2_FEATURE_GRAPHITE=1
      # Important:
      # keep the hostname graphite the same as
      # the name of the graphite docker-container
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      #- ICINGAWEB2_ADMIN_USER=icingaadmin
      #- ICINGAWEB2_ADMIN_PASS=icinga
      #- ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
      - DEFAULT_MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./icinga/cache:/var/cache/icinga2
      - ./icinga/certs:/etc/apache2/ssl:ro
      - ./icinga/etc/icinga2:/etc/icinga2
      - ./icinga/etc/icingaweb2:/etc/icingaweb2
      - ./icinga/lib/icinga:/var/lib/icinga2
      - ./icinga/lib/php/sessions:/var/lib/php/sessions
      - ./icinga/log/apache2:/var/log/apache2
      - ./icinga/log/icinga2:/var/log/icinga2
      - ./icinga/log/icingaweb2:/var/log/icingaweb2
      - ./icinga/log/mysql:/var/log/mysql
      - ./icinga/spool:/var/spool/icinga2
      # If you want to enable outbound e-mail, create the files
      #  - ./ssmtp/ssmtp.conf
      #  - ./ssmtp/revaliases
      #  and configure to your corresponding mail setup.
      #  See: https://github.com/jjethwa/icinga2#sending-notification-mails
      #- ./ssmtp/revaliases:/etc/ssmtp/revaliases:ro
      #- ./ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
  graphite:
    image: bebehei/graphite:latest
    restart: on-failure:5
    hostname: graphite
    volumes:
      - ./graphite/lib:/var/lib/graphite
      - ./graphite/log/apache:/var/log/apache2
      - ./graphite/log/graphite:/var/log/graphite
      - ./graphite/log/carbon:/var/log/carbon
  mysql:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql/data:/var/lib/mysql
      # If you have previously used the container's internal DB use:
      #- ./icinga/lib/mysql:/var/lib/mysql
